# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: buildConfig

trigger:
  - master

pr: 
  - master

variables:
  ShellProjectFolderName: 'BookSetup'  
  RepoName: 'BookRepo'
jobs: 
    - job: buildAndUnitest
      pool:
        vmImage: "windows-latest"
      steps:
        - task: NuGetToolInstaller@1
          displayName: install nuget tools
        - task: NuGetCommand@2
          displayName: restore nuget packages
          inputs:
           command: restore
           restoreSolution: '**/*.sln'
        - task: VSBuild@1
          displayName: build solution
          inputs:
           solution: '**/*.sln'
           platform: 'Any CPU'
           configuration: 'Release'
        - task: VisualStudioTestPlatformInstaller@1
          inputs:
            versionSelector: 'SpecificVersion'
            testPlatformVersion: '17.3.2'
        - task: VSTest@2
          displayName: 'VSTest'
          inputs:
           platform: 'Any CPU'
           configuration: 'Release'
           codeCoverageEnabled: True
           runInParallel: True
           runTestsInIsolation: True
           vsTestVersion: 'toolsInstaller'
           distributionBatchType: 'basedOnTestCases'
        - task: CopyFiles@2
          displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
          inputs: 
            SourceFolder: '$(Build.SourcesDirectory)/src/$(ShellProjectFolderName)/bin/Release'
            Contents: |
              **/*
              !**/*.pdb
            TargetFolder: '$(Build.ArtifactStagingDirectory)/$(RepoName)/bin'
        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: bookRepo


